#Change the volume location and makesure to load the nginx.conf
version: '2'
services:
  etcd:
    image: nginx
    container_name: nginx-lb
    hostname: nginx-lb
    volumes:
    - /nginx/nginx-lb.conf:/etc/nginx/nginx.conf
    ports:
    - 16443:16443
    restart: always
